### ISSUE TITLE
The Checklist for the upgrade withdrawals

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/AgoraMainNet#106]
- [x] Update code for agora-el
- [x] Update code in agora-cl
- [x] Upgrade agora-scan
- [x] Update code in boa-scan
- [x] Update code in agora-deposit-cli
- [x] Update code for agora-key-gen
- [x] Update code for agora-chain
- [x] Update documentation
- [x] Apply mainnet upgrade of agora-staking
- [x] Apply Mainnet Upgrade for Homepage
- [ ] Apply mainnet upgrade of agoranet
- [x] Apply mainnet upgrade of agora-chain
- [x] Apply mainnet upgrade of docs.bosagora.io
- [x] Check if Shanghai poker is carried out normally.
- [x] Check if the capella poker is carried out normally.
- [x] Inspect whether common budget issuance is normal before and after poker.
- [x] Inspect whether the reward issuance is normal before and after poker.
- [ ] Performance tests are conducted to ensure that the network is stable.

**Comment by Kang-Simon** [comment]
Apply Mainnet Upgrade for Homepage
https://github.com/bosagora/homepage/pull/154
https://github.com/bosagora/homepage/pull/155
